### ISSUE TITLE
Does this work? How do you use it?

### ISSUE THREAD

**Issue by kevzettler** [atsuya/parallel-mocha#1]
Needs Documentation in the README

**Comment by atsuya** [comment]
there is currently a bug that actually prevents it from running tests in parallel. and then i started to think if there is really a need for running mocha tests in parallel since mocha tests are pretty fast. do you have such need?

**Comment by kevzettler** [comment]
Yes I think It would be valuable. I have mocha tests that run against PhantomJS and another set against Selenium/WebdriverJs. I imagine Mocha is fast for standard unit tests but these high-level integration tests are long and running them in parallel would be a huge win.

**Comment by atsuya** [comment]
ah, but running mocha tests in node and browser are different. my intent of this library was to run tests in node.

**Comment by kevzettler** [comment]
I think there is a miscommunication. My tests are written and run in node.js They utilize node.js libraries that automatically drive a browser. These tests are executed from the terminal using node.js They take a long time to run because they are simulating a browser session experience. So yes. I am talking about running mocha from node.

**Comment by atsuya** [comment]
closing this since the pull request has been merged.
