### ISSUE TITLE
wish: make the number of parallel processes configurable.

### ISSUE THREAD

**Issue by markstos** [atsuya/parallel-mocha#3]
Looks like it's hardcoded to "2" now.  Using `-j` for this option is fairly standard.

**Comment by atsuya** [comment]
can you try to see if `-p` option works?

**Comment by markstos** [comment]
I've re-read the code now, and it appears that "2" is a default which can
be overwritten. Great!  Here a couple suggestions to improve the situation
further:
- Document the existence of -p in the README file.
- In Runner.js, where "2" is hardcoded, using the "defaults" feature of
  Underscore rather than 'extends'. That will make it clearer that you are
  setting defaults there, which may be overridden:
  http://underscorejs.org/#defaults

**Comment by atsuya** [comment]
i updated the doc accordingly. for an use of defaults instead of extends, i leave it as is for now since i don't feel the strong appeal to change it.

thanks for the suggestions :pray:
